### ISSUE TITLE
Manual (re-)indexing widget

### ISSUE THREAD

**Issue by lukasbestle** [getkirby-plugins/algolia-plugin#1]
After the plugin is installed, there is currently no way to easily index the site other than putting `algolia()->index()` somewhere. A dashboard widget could help here.

What do you think, @bastianallgeier?

**Comment by pedroborges** [comment]
@lukasbestle I can tweak the widget used by Auto Git and submit a PR. My proposal is:

<img width="306" alt="algolia" src="https://cloud.githubusercontent.com/assets/688309/16876358/f636ed3e-4a79-11e6-9d47-7070cda00550.png">

Is that in the right direction? Are there any information you'd find useful to display on the widget body?

**Comment by lukasbestle** [comment]
Thank you for your offer. I will create a widget today. :)

**Comment by pedroborges** [comment]
That will come in handy!

I need such feature because one of my sites only receive changes from a staging server. The main reason I added hooks to Auto Git was to update search index after pulling changes.

**Comment by lukasbestle** [comment]
We use a similar process for the Kirby site, which is why that totally makes sense. :)

**Comment by lukasbestle** [comment]
There's now a widget in the new plugin version 1.1.0. Let me know what you think. :)

**Comment by sjelfull** [comment]
@lukasbestle I can't get it to show up in the dashboard. Running 2.2.3. Anything special I need to do?

**Comment by lukasbestle** [comment]
Yes: Upgrade to Kirby 2.3.1, the widget requires Kirby 2.3.
