### ISSUE TITLE
Add setSettings method

### ISSUE THREAD

**Issue by olach** [getkirby-plugins/algolia-plugin#10]
This plugin allows you to set some options when calling the `search` method. But some settings in Algolia are not allowed to be set with the `search` method, instead the `setSettings` method has to be used.

Look here:
https://www.algolia.com/doc/api-reference/api-parameters/

Is there a way that I have missed to call the `setSettings` method from this plugin, or does this have to be implemented?

**Comment by lukasbestle** [comment]
Index settings aren't something you'd need to define from the site. For the Kirby site (which also uses Algolia), we set those once via their web interface and never needed to touch them again.
So I don't see a use-case why the plugin would need support for this. Please reopen this issue if you disagree.
