### ISSUE TITLE
Algolia index only takes the first between `categories_en` and `categories_it`

### ISSUE THREAD

**Issue by gvocale** [getkirby-plugins/algolia-plugin#12]
I'm running into a weird issue.

In my `config.php` I have:

    c::set('algolia.templates', array(
      'product' => array(
        'filter' => function ($page) {
          return $page->isVisible();
        },
        'fields' => array(
          'category_en' => array('split', '/'),
          'category_it' => array('split', '/'),
          'description',
          'title'
        )
      ),
    ));

I then refresh the Search index via the widget. When I check the index through the Algolia dashboard, for each item, only `category_en` has been added. `Category_is` went missing, but `description` and `title` are there!

If I do invert the order in `config.php` and refresh the index, then `category_it` is added, but I miss `category_en`. `Description` and `title` are still there.

Any idea of what could be?

**Comment by gvocale** [comment]
Seems like I've manage to fix this issue going this other route:

    c::set('algolia.templates', array(
      'product' => array(
        'filter' => function ($page) {
          return $page->isVisible();
        },
        'fields' => array(
          'category_it' => function ($page) {
            return $page->category_it()->split('/');
          },
          'category_en' => function ($page) {
            return $page->category_en()->split('/');
          },
          'description',
          'title'
        )
      ),
    ));

**Comment by lukasbestle** [comment]
Hm, I read through the method that is responsible for building the data and couldn't find the reason there. I will try to debug this.

**Comment by lukasbestle** [comment]
This is now fixed in a new release v1.1.3.
