### ISSUE TITLE
only works when directory is renamed to 'algolia'

### ISSUE THREAD

**Issue by puckey** [getkirby-plugins/algolia-plugin#14]
It took a while to get this plugin working. I had to rename the directory from 'algolia-plugin' to 'algolia'. Is this perhaps how Kirby infers the php filename to load?

Perhaps this should be added to the docs? Or (if it is a filename inferring problem) perhaps algolia.php should be renamed to algolia-plugin.php?

**Comment by lukasbestle** [comment]
That's right. All of our official plugins have that naming scheme at the moment.

Kirby 3 will fix this by loading the file `index.php`, so it shouldn't matter what the directory name is.
