### ISSUE TITLE
Undefined variable: $kirby

### ISSUE THREAD

**Issue by sjelfull** [getkirby-plugins/algolia-plugin#4]
In algolia.php#L31, $kirby is referenced. Everywhere else, you use kirby().

**Comment by lukasbestle** [comment]
It should actually work anyway as `$kirby` is defined in plugins, but see [my comment on the widget issue](https://github.com/getkirby-plugins/algolia-plugin/issues/1#issuecomment-234491804).

**Comment by sjelfull** [comment]
I'm getting an error that it's not defined, though:

**Notice: Undefined variable: kirby in /Projects/src/site/plugins/algolia/algolia.php on line 31**
Call Stack
    Time    Memory  Function    Location
1   0.0002  376344  {main}( )   .../server.php:0
2   0.0190  499848  require( '/Projects/src/panel/index.php' ) .../server.php:106
3   0.0304  1211672 Kirby\Panel->__construct( ) .../index.php:48
4   0.0509  2974016 Kirby->plugins( )   .../panel.php:116
5   0.0509  2974608 Kirby->plugin( )    .../kirby.php:433
6   0.0511  2989144 include_once( '/Projects/src/site/plugins/algolia/algolia.php' )   .../kirby.php:460

**Fatal error: Uncaught Error: Call to a member function set() on null in /Projects/src/site/plugins/algolia/algolia.php on line 31**

**Error: Call to a member function set() on null in /Projects/src/site/plugins/algolia/algolia.php on line 31**
Call Stack
    Time    Memory  Function    Location
1   0.0002  376344  {main}( )   .../server.php:0
2   0.0190  499848  require( '/Projects/src/panel/index.php' ) .../server.php:106
3   0.0304  1211672 Kirby\Panel->__construct( ) .../index.php:48
4   0.0509  2974016 Kirby->plugins( )   .../panel.php:116
5   0.0509  2974608 Kirby->plugin( )    .../kirby.php:433
6   0.0511  2989144 include_once( '/Projects/src/site/plugins/algolia/algolia.php' )   .../kirby.php:460

Turns out upgrading as mentioned in #1 fixes the problem. I've added the requirement to the readme, incase anyone else face this problem.
