### ISSUE TITLE
The Algolia index is not auto updated when deleting parent with subpages from the panel

### ISSUE THREAD

**Issue by felixbridell** [getkirby-plugins/algolia-plugin#8]
I noticed that the plugin does not update the algolia index if I delete a page with subpages. The parent page is deleted from the Algolia index but not the subpages.

**Comment by lukasbestle** [comment]
Good point! Looks like it wasn't possible to delete pages with subpages in the Panel back when I implemented this feature for this plugin. Should be easy to fix though. :)
